### ISSUE TITLE
Error string conversion on load

### ISSUE THREAD

**Issue by Dezmonteri** [ESOUIMods/DarkUI#1]
Hi, thanks for your Great work, unfortunatly there was an error appeart yesterday
![Снимок экрана 2022-04-19 230539](https://user-images.githubusercontent.com/25460150/164118009-b4db3a77-bd15-4b23-9d59-be7c522dd204.jpg)
Affective version 2.70

**Comment by Sharlikran** [comment]
Should be fixed as of https://github.com/ESOUIMods/DarkUI/commit/55c30ec7727d26b4f47374572576093e5c4b1682
